### ISSUE TITLE
Apply security updates to server

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#136]
Ensure known vulnerabilities are patched.

**Comment by martinratinaud** [comment]
Ok, I asked Beat community and here is what I got so far

- [ ] add `server_tokens off;` to nginx config
- [ ] Fix openSSH based on https://nvd.nist.gov/vuln/search/results?form_type=Advanced&cves=on&cpe_version=cpe:/a:openbsd:openssh:7.9p1

**Comment by MattiSG** [comment]
- Main website is now serverless on Scalingo, no more security updates to handle.
- Contribute website got security updates applied by @martinratinaud. There are still some vulnerabilities open:
```
  cpe:/a:openbsd:openssh:7.9p1: 
    	EXPLOITPACK:98FE96309F9524B8C84C508837551A19	5.8	https://vulners.com/exploitpack/EXPLOITPACK:98FE96309F9524B8C84C508837551A19	*EXPLOIT*
    	EXPLOITPACK:5330EA02EBDE345BFC9D6DDDD97F9E97	5.8	https://vulners.com/exploitpack/EXPLOITPACK:5330EA02EBDE345BFC9D6DDDD97F9E97	*EXPLOIT*
    	EDB-ID:46516	5.8	https://vulners.com/exploitdb/EDB-ID:46516	*EXPLOIT*
    	EDB-ID:46193	5.8	https://vulners.com/exploitdb/EDB-ID:46193	*EXPLOIT*
    	CVE-2019-6111	5.8	https://vulners.com/cve/CVE-2019-6111
    	1337DAY-ID-32328	5.8	https://vulners.com/zdt/1337DAY-ID-32328	*EXPLOIT*
    	1337DAY-ID-32009	5.8	https://vulners.com/zdt/1337DAY-ID-32009	*EXPLOIT*
    	PACKETSTORM:151227	0.0	https://vulners.com/packetstorm/PACKETSTORM:151227	*EXPLOIT*
```
- Potential further update would be of the OS.

**Comment by martinratinaud** [comment]
In order to finalize this fix, we need to upgrade the server.

In order to do this, I've reviewed the whole ops of all concerned apps

- Proxy https://github.com/OpenTermsArchive/ops/pull/2
- Contribution tool https://github.com/OpenTermsArchive/contribution-tool/pull/49
- Legacy API https://github.com/OpenTermsArchive/api-legacy/pull/48

**Comment by MattiSG** [comment]
Does this new `ops` repo mean that we also intend to migrate the `ops` part of the Core Open Terms Archive repo to it? I am not sure I understand what this repository aims at consolidating 🙂

**Comment by martinratinaud** [comment]
Config for the Nginx proxy (which is actually handling redirection for legacy api and contribution tool) is currently held in the ambnum ops repository.

This repo does not aim at consolidating OTA ops. I just figured it was better to have this in OpenTermsArchive org instead of ambanum's one.

I don't think ops should be moved from OTA core to this repo.

But it seems the purpose of this repo is not clear enough, so I can rename `proxy-ops` or `proxy`.

What do you think?

**Comment by MattiSG** [comment]
Yes, let's rename this to `reverseproxy-ops` 👍

**Comment by MattiSG** [comment]
Perfect, thanks @martinratinaud! 🙂
