### ISSUE TITLE
Move all locale files to a dedicated folder

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#55]
- [ ] `pages/${page}.${locale}.mdx` → `src/translations/${locale}/${page}.mdx`
- [ ] `public/locales/common.json` → `src/translations/${locale}/${page}.json` + `src/translations/${locale}/_common.json`
- [ ] `pages/contribute/${page}.${locale}.mdx` → `src/translations/contribute/${locale}/${page}.mdx`
- [ ] `public/locales/contribute.json` → `src/translations/${locale}/contribute/${page}.json`

- [ ] Document in CONTRIBUTING that we use one translation file per page, with the same name for the TSX, the l10n JSON file, and the folder name containing the MDX templates.

**Comment by martinratinaud** [comment]
I believe having a specific file per page is more difficult to maintain.
Also what happens when a translation lies within a component ?

My recommandation would be to have one file only per module and a prefix system like

- `<module>:<component or page>.<something>.<something>` -> we need to define this something

That would lead to
`common:thanks_page.seo.title`
`subscription:subscribe_form.email.placeholder`

Even if the file becomes big, crowdin will remove the complexity of managing that
