### ISSUE TITLE
Make logo more significant

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#63]
Make visible a notion of history / archival.

### Publish as PNG files

On the Media page (depends on #64).

- [x] Publish raster high res version white with transparent background
- [x] Publish raster high res version black with transparent background
- [x] Publish square raster high res version black on transparent
- [x] Publish square raster high res version white on transparent

At least 1024px on the smallest dimension.
Optimise the PNGs with ImageOptim.

### Update the logo on

- [x] Website
- [x] Favicon
- [x] Twitter
- [x] OTA organisation on GitHub

**Comment by MattiSG** [comment]
What about adding an arrow to the bottom of the half-circle to show a counter-clockwise movement? 🙂

**Comment by clementbiron** [comment]
As we have discussed, here are proposals for the evolution of the logo that take into account your feedback:
- signify the notion of archive / history
- reduce the possibility of confusion with a burger menu icon on the open terms archive website

The tracks shown below may be subject to change depending on your feedback, so let's talk 💬 ! @MattiSG @Ndpnt @martinratinaud @trujilloelsa 

![current](https://user-images.githubusercontent.com/364319/142020096-60a54c56-e048-41b3-9ae0-68b45e97787a.png)

![track1](https://user-images.githubusercontent.com/364319/142020146-2943b22c-3ee5-4189-803b-6081f50c874f.png)
In my opinion this track makes understanding more complicated, too complex. 🗑
 
![track2](https://user-images.githubusercontent.com/364319/142020155-5e053f3d-c483-4b39-a272-b4905382e65b.png)
If i had to choose one it would be this one because it's keep the logo simple with clearly identifiable notion of archive / history. But i'm not totaly satisfied :
- we loose the "open source" symbol with the "open" O 
- i am not completely comfortable with an arrow pointing backwards, towards "nothing"  

![track3](https://user-images.githubusercontent.com/364319/142020167-d82ac174-e55b-483a-b33c-41af19a453f0.png)
The main promise of OTA is to archive, not to provide a search index, this track seems to me beside the subject. 🗑

**Comment by martinratinaud** [comment]
Track 2 is my favorite
- I didn't see the O was for Open source so not a problem to me
- I understand this arrow as "repetition", so it's good I think

**Comment by Ndpnt** [comment]
I made some variants, as I find it easier than explaining in writing, it is just ideas:
![4](https://user-images.githubusercontent.com/1098708/142378938-7b9c5543-8239-4c7c-989b-a8714d0fb96e.png)

This one to increase the difference with a burger menu icon:

![3](https://user-images.githubusercontent.com/1098708/142378941-2913b8d5-45a1-4956-91d1-ba434ebefa7c.png)

With the followings you keep (more or less) the open source symbol:

![2](https://user-images.githubusercontent.com/1098708/142378944-bd4f5de5-2738-4b75-9796-d871b52a62a3.png)


![1](https://user-images.githubusercontent.com/1098708/142378947-d46c5d90-d3ef-4a0c-b9cb-19bbe59c4d13.png)

What do you think?

**Comment by MattiSG** [comment]
Nice, thanks Clement!

Track 2 definitely has my preference. I like the second proposal in your last message, it is the one I had in mind.

I think the last is out because the arrow should be counter clockwise to show that we go back in time, and the first is not very clear to me.

I was inspired by macOS’ Time Machine icon.

**Comment by MattiSG** [comment]
Oops sorry just saw the author of the second set of proposals, not as easy over email  ;)

So I was referring to track 2 by clement and suggestion 2 by @Ndpnt as the ones I had In mind.

**Comment by trujilloelsa** [comment]
Thanks for your work! 
Evolution track 2 has my preference. I don't mind getting rid of the open O, which doesn't explicitely refer to "open source", in my opinion. I'm also uncomfortable with the arrow pointing backwards. May the arrow directly point on the text ?
I must admit I also support the Evolution track 3, as Open Terms Archive is meant to be explored by its users, which makes this magnifying glass symbol significant.

**Comment by Ndpnt** [comment]
@clementbiron Can you provide us a version with plain arrow ?
And also, a pixel perfect version ?

Do not hesitate to call me If you want to discuss about that :)

**Comment by clementbiron** [comment]
Thanks all for your feeedback, let's continue.

Track 2 seems to be preferred, so I continue to explore in this direction with a plain arrow and shapes styles.

![track2-2](https://user-images.githubusercontent.com/364319/144059899-02999b0d-7d9d-41d2-8e6f-2aa6ff1c5d6e.png)
Track 2.2 with plain arrow and rounded shapes. My favorite because it's it is softer, less rough and it is a slightly smaller change than track 2.3. 


![track2-3](https://user-images.githubusercontent.com/364319/144061302-abdb3913-a5cc-4f59-938a-a367e11d8c96.png)
Track 2.3 with plain arrow and sharpe shapes.

@Ndpnt do these tracks meet your expectations?

I think it's not necessary to publish here the whole logo evolution test board, ~40 tracks ( it will probably make us go in all directions) but I keep it available for those who want to see.

**Comment by Ndpnt** [comment]
@clementbiron Yep, thanks 😉.

**Comment by clementbiron** [comment]
Following our working session, here are the new tracks

More or less closed circle
![track2-4-1](https://user-images.githubusercontent.com/364319/145190615-8cc4e9e2-82d6-47d6-bcba-25497f7c8705.png)
![track2-4-2](https://user-images.githubusercontent.com/364319/145190619-f308fe36-1be7-4847-9c8a-20b8b0fce982.png)

Variation in the file icon
![track2-5-1](https://user-images.githubusercontent.com/364319/145190621-55664b89-2d3f-40a3-81c0-370b2a00614b.png)
![track2-5-2](https://user-images.githubusercontent.com/364319/145190623-717729c4-3bdd-4c69-8461-134bd02f1efb.png)

Vertical text
![track2-6-1](https://user-images.githubusercontent.com/364319/145190624-4887ddf3-c7ed-4c3b-93b4-8fb22efbbcac.png)
![track2-6-2](https://user-images.githubusercontent.com/364319/145190625-9f09b68c-2174-4264-98ae-68ce69c3a5b4.png)

In my opinion, track 2.5.2 is the best.

**Comment by martinratinaud** [comment]
+1 for 2.5.2

**Comment by Ndpnt** [comment]
2.5.2 too

**Comment by trujilloelsa** [comment]
2.5.2 too!

**Comment by clementbiron** [comment]
2.5.2 seems to me to be the adopted track 🥳 

@MattiSG see below a version with the shape as hight as the text, which in my opinion is not convincing. Could you confirm that i cango ahead to start the implementation of the 2.5.2 ?

![track2-7-1](https://user-images.githubusercontent.com/364319/145795126-ecc38560-f13f-4e4d-ae7c-5b2b0636836d.png)

Thanks all for feedback during this process.

**Comment by MattiSG** [comment]
Let me just quickly ask @michielbdejong from @tosdr if it would be okay to use the exact same shape (in terms of lines length ratio) for the ToS symbol inside the circle as @tosdr does.

@clementbiron do you think this shape (not the colors, of course) would fit in the circle: ![](https://s3.tosdr.org/branding/tosdr-icon-32.svg)?

I would love for this ecosystem to come with a unified graphic language for representing common elements!

**Comment by clementbiron** [comment]
See below a try with the Tosdr logo shape. I think it doesn't work, the tosdr shape displays better in larger size or in color, which is not the case in our use.

![track2 8 1](https://user-images.githubusercontent.com/364319/145804563-7d6a09c6-f441-406d-85dc-c28978bea4e8.png) 

What we can do easily is to take the shape drawn by the end of the lines on their width, in a way the shape becomes almost identical but with a different weight (the changes I made to get there are really minor).

![track2-8-2](https://user-images.githubusercontent.com/364319/145805505-f50a8ec3-ca69-45cc-8a0f-16a147352bde.png)

As it is not necessarily easy to explain, I put an image below to help understand.

![diff](https://user-images.githubusercontent.com/364319/145806229-e2b31de2-c27f-4211-bfde-1ef3c731ea9f.png)

**Comment by MattiSG** [comment]
Thanks @clementbiron.

I am personally not shocked at all by 2.8.1, but I don't want to delay more finishing that track of work and the associated delivery of #62. Let's go with 2.8.2 (very minor change from 2.5.2 indeed) and the associated 2.7.1 for a square version that we can use in formats where it will be needed! 👍

Thank you very much for your work on this topic, the result is great!

**Comment by clementbiron** [comment]
OK, thank you all for this work 💪
The new version of the logo is now deploy on Twitter and GitHub account. It will be implemented on the website in the next hours with the possibility to download the .svg and the png files.
