### ISSUE TITLE
Support arbitrary destination repositories in contribution UI

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive.org#92]
- Remove the last links to the Contribute UI from the homepage.
- Read the destination repository of issues from the `destination` query parameter. Take `services-all` as a default.

### Accepted limitations

- We assume that it will be very unlikely that malformed URLs are used, and that the volume of misdirected issues will be low.

**Comment by martinratinaud** [comment]
PR is to be reviewed

I decided to not use `services-all` as a default on the home page as it should never happen. In case it happens, an info message is displayed.
I'd rather let the user know that there is a mistake instead of silently redirecting (but I still can change it)

On a direct access to the detail page though, I automatically rewrite the url with `destination=OpenTermsArchive/services-all` in order to support the urls already created in the Github issues of `services-all` repository

In case of a malformed destination, instead of creating the issue, it will automatically open a prefilled email (with a mailto) with the github issue text to be sent to contribute@opentermsarchive.org

**Comment by martinratinaud** [comment]
Issue has been closed automatically is it has been merged into `develop`

This should happen only when it is merged into `main` so reponeing

**Comment by martinratinaud** [comment]
Tested on preprod with url https://preprod.opentermsarchive.org/en/contribute/service?destination=ambanum%2Ftest-repo2&documentType=Privacy%20Policy&expertMode=true&name=Scalingo&selectedCss[]=.text-4xl&selectedCss[]=section%20%3E%20.bg-sc-blue-1-30&step=2&url=https%3A%2F%2Fscalingo.com%2Fprivacy-policy

It created a new comment in https://github.com/ambanum/test-repo2/issues/1 successfully

**Comment by martinratinaud** [comment]
@MattiSG It's deployed on production and url is accessible using

https://www.opentermsarchive.org/en/contribute?destination=<org>/<repo>

or in french

https://www.opentermsarchive.org/fr/contribute?destination=<org>/<repo>

Let me know if everything is ok

**Comment by MattiSG** [comment]
That does the job 🙂
